### ISSUE TITLE
attempt to divide by zero - 10k dataset

### ISSUE THREAD

**Issue by tivrfoa** [RagnarGrootKoerkamp/1brc#4]
About the bug that I mentioned on Twitter:

```
time ./bin/one-billion-row-challenge --print > l.out
thread 'main' panicked at /rustc/62d7ed4a6775c4490e493093ca98ef7c215b835b/library/core/src/num/mod.rs:335:5:
attempt to divide by zero
stack backtrace:
   0: rust_begin_unwind
             at /rustc/62d7ed4a6775c4490e493093ca98ef7c215b835b/library/std/src/panicking.rs:647:5
   1: core::panicking::panic_fmt
             at /rustc/62d7ed4a6775c4490e493093ca98ef7c215b835b/library/core/src/panicking.rs:72:14
   2: core::panicking::panic
             at /rustc/62d7ed4a6775c4490e493093ca98ef7c215b835b/library/core/src/panicking.rs:144:5
   3: one_billion_row_challenge::main
   4: core::ops::function::FnOnce::call_once
             at /rustc/62d7ed4a6775c4490e493093ca98ef7c215b835b/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

https://drive.google.com/file/d/1sVA0yUuo5oZoeAQFoPJgaF0cQnq4fPCr/view?usp=sharing

https://drive.google.com/file/d/1hB72HaFC87Pjykv1mu0CIF4kXO5Qjefs/view?usp=sharing

**Comment by tivrfoa** [comment]
active toolchain
----------------

nightly-x86_64-unknown-linux-gnu (default)
rustc 1.77.0-nightly (62d7ed4a6 2024-01-11)

**Comment by RagnarGrootKoerkamp** [comment]
I get `access denied` on the files.

It's weird because my code doesn't do any division by 0, only by non-0 constants. Maybe the bug is in the PHF construction.
Maybe you can run with `RUST_BACKTRACE=full`? The current stacktrace doesn't give me the location in my own code where things fail.

(I did verify that things work as expected for me locally in the master branch.)

**Comment by tivrfoa** [comment]
> I get `access denied` on the files.
> 

Request access to the file and I will release it.
One contains 200 millions with up to 10k cities.
The other is a correct output, so you can compare.

**Comment by tivrfoa** [comment]
> I get `access denied` on the files.
> 

I gave you access. Try again, please.

**Comment by RagnarGrootKoerkamp** [comment]
Hmm; it doesn't crash on the full dataset, but it does crash on your smaller one. *Very* weird.
Something is wrong with the perfect hash function, but I don't have time now to figure it out.

Is it simply using a prefix of `measurements3.txt`?

**Comment by tivrfoa** [comment]
> Hmm; it doesn't crash on the full dataset, but it does crash on your smaller one. _Very_ weird. Something is wrong with the perfect hash function, but I don't have time now to figure it out.
> 
> Is it simply using a prefix of `measurements3.txt`?

I created like this: `./create_measurements3.sh 200000000`

But it's a different output every time.
